packages:
  - packages/*

linkWorkspacePackages: true

allowBuilds:
  esbuild: true
  netlify-cli: false
  nx: true
  sharp: false
  unix-dgram: false

minimumReleaseAgeExclude:
  - '@tryghost/errors@3.3.8'
  - '@tryghost/pretty-cli@3.3.8'
