packages:
  - packages/*

linkWorkspacePackages: true

allowBuilds:
  esbuild: true
  netlify-cli: false
  nx: true
  sharp: false
  unix-dgram: false

minimumReleaseAgeExclude:
  - '@tryghost/errors'
  - '@tryghost/pretty-cli'

patchedDependencies:
  '@netlify/config': patches/@netlify__config.patch
  netlify-cli: patches/netlify-cli.patch
